Add an argument check to postinst to avoid it running when it shouldn't

diff --git a/installer/deb/scripts/postinst b/installer/deb/scripts/postinst
--- a/installer/deb/scripts/postinst
+++ b/installer/deb/scripts/postinst
@@ -71,13 +71,29 @@ set_local_dns() {
     echo "DNS configuration complete."
 }
 
-# Create MassaStation configuration directories.
-mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
-mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
-mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/logs || fatal "logs directory creation failed."
-mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."
+main() {
+    # Create MassaStation configuration directories.
+    mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
+    mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
+    mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/logs || fatal "logs directory creation failed."
+    mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."
 
-ping -c 1 -t 1 test.massa &> /dev/null || set_local_dns
+    ping -c 1 -t 1 test.massa &> /dev/null || set_local_dns
 
-# Setcap massastation to allow binding to privileged ports (80, 443).
-setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/massastation || fatal "Failed to setcap massastation."
+    # Setcap massastation to allow binding to privileged ports (80, 443).
+    setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/massastation || fatal "Failed to setcap massastation."
+}
+
+case "$1" in
+    configure)
+        main
+        ;;
+    abort-upgrade|abort-remove|abort-deconfigure)
+        ;;
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+        ;;
+esac
+
+exit 0
