Improve postinstall error handling.

diff --git a/installer/deb/scripts/postinst b/installer/deb/scripts/postinst
--- a/installer/deb/scripts/postinst
+++ b/installer/deb/scripts/postinst
@@ -3,6 +3,9 @@
 # Postinstall script for MassaStation installer on Linux
 # It configures dnsmasq to resolve .massa domains to localhost and generates a certificate for MassaStation.
 
+# `set -e` causes the script to exit if any command fails.
+set -e
+
 # Set MassaStation configuration directories.
 export MASSASTATION_CONFIG_DIR=/usr/local/share/massastation
 export MASSASTATION_CERT_DIR=/etc/massastation/certs
@@ -24,31 +27,31 @@ configure_network_manager() {
     local dns="$(grep '^dns=' /etc/NetworkManager/NetworkManager.conf | sed 's/^dns=//')"
     case "$dns" in
         dnsmasq) ;;
-        "") sed -i 's/^\[main\]$/\[main\]\ndns=dnsmasq/g' /etc/NetworkManager/NetworkManager.conf || fatal "Failed to configure NetworkManager." ;;
-        *) sed -i 's/^dns=.*/dns=dnsmasq/' /etc/NetworkManager/NetworkManager.conf || fatal "Failed to configure NetworkManager." ;;
+        "") sed -i 's/^\[main\]$/\[main\]\ndns=dnsmasq/g' /etc/NetworkManager/NetworkManager.conf || fatal "Failed to set dns=dnsmasq in NetworkManager.conf." ;;
+        *) sed -i 's/^dns=.*/dns=dnsmasq/' /etc/NetworkManager/NetworkManager.conf || fatal "Failed to change dns= to dnsmasq in NetworkManager.conf." ;;
     esac
 }
 
 # Configure dnsmasq to resolve .massa domains to localhost.
 configure_dnsmasq() {
     mkdir -p /etc/NetworkManager/dnsmasq.d/ || fatal "Failed to create dnsmasq.d directory."
-    echo "address=/.massa/127.0.0.1" > /etc/NetworkManager/dnsmasq.d/massa.conf || fatal "Failed to configure dnsmasq."
+    echo "address=/.massa/127.0.0.1" > /etc/NetworkManager/dnsmasq.d/massa.conf || fatal "Failed to set dnsmasq to resolve .massa domains to localhost."
 }
 
 # Update /etc/resolv.conf to use dnsmasq.
 update_resolv_conf() {
     mv /etc/resolv.conf /etc/resolv.conf.bak_massa || fatal "Failed to backup resolv.conf."
 
-    ln -s /var/run/NetworkManager/resolv.conf /etc/resolv.conf || fatal "Failed to update resolv.conf."
+    ln -s /var/run/NetworkManager/resolv.conf /etc/resolv.conf || fatal "Failed to update resolv.conf symlink."
     systemctl restart NetworkManager || fatal "dnsmasq service failed to restart"
 }
 
 # Install dnsmasq and configure it to resolve .massa domains to localhost.
 set_local_dns() {
     case $(lsof -i :53 | sed -n 2p | sed 's/[[:space:]].*$//') in
-        "") (configure_network_manager || fatal "Failed to configure NetworkManager.") && (configure_dnsmasq || fatal "Failed to configure dnsmasq.") && (update_resolv_conf || fatal "Failed to update resolv.conf.") ;;
-        dnsmasq) (configure_dnsmasq || fatal "Failed to configure dnsmasq.") && (update_resolv_conf || fatal "Failed to update resolv.conf.") ;;
-        systemd-r) (configure_network_manager || fatal "Failed to configure NetworkManager.") && (configure_dnsmasq || fatal "Failed to configure dnsmasq.") && (update_resolv_conf || fatal "Failed to update resolv.conf.") ;;
+        "") configure_network_manager && configure_dnsmasq && update_resolv_conf ;;
+        dnsmasq) configure_dnsmasq && update_resolv_conf ;;
+        systemd-r) configure_network_manager && configure_dnsmasq && update_resolv_conf ;;
         *) fatal "Unsupported DNS server" ;;
     esac
     echo "DNS configuration complete."
@@ -69,10 +72,10 @@ generate_certificate() {
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
 
-ping -c 1 -t 1 test.massa &> /dev/null || set_local_dns || exit 1
+ping -c 1 -t 1 test.massa &> /dev/null || set_local_dns
 
 if [[ ! -f $MASSASTATION_CERT_DIR/cert.pem || ! -f $MASSASTATION_CERT_DIR/cert-key.pem ]]; then
-    generate_certificate || fatal "certificate generation failed."
+    generate_certificate
 fi
 
 # Setcap massastation-server to allow binding to privileged ports (80, 443).
