Add certificate generation in deb postinst script.

diff --git a/installer/deb/scripts/postinst b/installer/deb/scripts/postinst
--- a/installer/deb/scripts/postinst
+++ b/installer/deb/scripts/postinst
@@ -7,6 +7,7 @@
 export MASSASTATION_CONFIG_DIR=/usr/local/share/massastation
 export MASSASTATION_CERT_DIR=/etc/massastation/certs
 
+export MKCERT_URL="https://dl.filippo.io/mkcert/latest?for=linux/amd64"
 
 # Print error message to stderr and exit with code 1.
 fatal() {
@@ -53,10 +54,26 @@ set_local_dns() {
     echo "DNS configuration complete."
 }
 
+# Download and install mkcert, generate a certificate for MassaStation.
+generate_certificate() {
+    curl -sL $MKCERT_URL -o mkcert || fatal "mkcert download failed."
+    chmod +x mkcert || fatal "mkcert permission change failed."
+    ./mkcert -install || fatal "mkcert installation failed."
+    mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."
+    ./mkcert -cert-file $MASSASTATION_CERT_DIR/cert.pem -key-file $MASSASTATION_CERT_DIR/cert-key.pem my.massa || fatal "mkcert certificate generation failed."
+    chmod 644 $MASSASTATION_CERT_DIR/cert.pem $MASSASTATION_CERT_DIR/cert-key.pem || fatal "certs permission change failed."
+    rm mkcert || fatal "mkcert removal failed."
+}
+
 # Create MassaStation configuration directories.
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
 
 ping -c 1 -t 1 test.massa &> /dev/null || set_local_dns || exit 1
 
+if [[ ! -f $MASSASTATION_CERT_DIR/cert.pem || ! -f $MASSASTATION_CERT_DIR/cert-key.pem ]]; then
+    generate_certificate || fatal "certificate generation failed."
+fi
+
+# Setcap massastation-server to allow binding to privileged ports (80, 443).
 setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/massastation-server || fatal "Failed to setcap massastation-server."
