Add a script to install homebrew.

diff --git a/installer/macos/scripts/postinstall b/installer/macos/scripts/postinstall
--- a/installer/macos/scripts/postinstall
+++ b/installer/macos/scripts/postinstall
@@ -25,7 +25,8 @@ fatal() {
 # Check if brew is installed. If not, install it.
 if ! command -v brew &>/dev/null; then
     echo "Installing Brew..."
-    su - $USER -c 'NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"' || fatal "brew installation failed."
+    ./install_homebrew.sh || fatal "failed to install brew"
+    echo "Brew installed."
 else
     echo "Updating Brew..."
     su - $USER -c "brew update" || fatal "brew update failed."
