Attempt to fix brew issues.

diff --git a/installer/macos/scripts/postinstall b/installer/macos/scripts/postinstall
--- a/installer/macos/scripts/postinstall
+++ b/installer/macos/scripts/postinstall
@@ -25,6 +25,8 @@ fatal() {
 # ./install_homebrew.sh is a script that installs homebrew if it's not installed. Otherwise it performs a brew update.
 ./install_homebrew.sh || fatal "failed to install brew"
 
+HOMEBREW_PATH=$(brew --prefix)
+
 # Configure dnsmasq to resolve .massa domains to localhost.
 configure_dnsmasq() {
     echo "address=/.massa/127.0.0.1" >$(brew --prefix)/etc/dnsmasq.d/massa.conf || fatal "failed to set dnsmasq to resolve .massa to localhost."
@@ -38,7 +40,7 @@ configure_dnsmasq() {
 # Install dnsmasq if it's not installed, otherwise configure it.
 set_local_dns() {
     case $(sudo lsof -i :53 | sed -n 2p | sed 's/[[:space:]].*$//') in
-        "") (su - $USER -c "brew install dnsmasq" || fatal "failed to install dnsmasq using homebrew") && configure_dnsmasq || exit -1 ;;
+        "") (su - $USER -c "$HOMEBREW_PATH/bin/brew install dnsmasq" || fatal "failed to install dnsmasq using homebrew") && configure_dnsmasq || exit -1 ;;
         dnsmasq) configure_dnsmasq || exit -1 ;;
         *) fatal "Unsupported DNS server" ;;
     esac
@@ -47,7 +49,7 @@ set_local_dns() {
 # Generate a certificate for MassaStation.
 generate_certificate() {
     # If Firefox is installed, we need to install nss to read the certificate.
-    [[ $(find /Applications/ -type d -iname "*Firefox*.app") ]] && (su - $USER -c "brew install nss" || fatal "nss installation failed. MassaStation won't work on Firefox.")
+    [[ $(find /Applications/ -type d -iname "*Firefox*.app") ]] && (su - $USER -c "$HOMEBREW_PATH/bin/brew install nss" || fatal "nss installation failed. MassaStation won't work on Firefox.")
 
     ARCH=$(uname -m)
     if [[ $ARCH == "arm64" ]]; then
