Add a check for nss install and add git installation if needed

diff --git a/installer/macos/scripts/postinstall b/installer/macos/scripts/postinstall
--- a/installer/macos/scripts/postinstall
+++ b/installer/macos/scripts/postinstall
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Postinstall script for MassaStation installer on MacOS
-# It configures dnsmasq to resolve .massa domains to localhost and other configuration (create folders, install dependencies...)
+# It configures /etc/hosts to resolve station.massa to localhost, create required folders, install dependencies...
 
 set -e
 
@@ -23,9 +23,16 @@ fatal() {
 
 HOMEBREW_PATH=$(brew --prefix)
 
-# nss contains certutil which is used to generate a certificate.
-su - $USER -c "$HOMEBREW_PATH/bin/brew install nss" || fatal "failed to install nss using homebrew"
+# Install git using homebrew if it's not installed.
+if ! command -v git >/dev/null 2>&1; then
+    su - $USER -c "$HOMEBREW_PATH/bin/brew install git" || fatal "failed to install git using homebrew"
+fi
 
+# Install nss using homebrew if it's not installed.
+if ! command -v certutil >/dev/null 2>&1; then
+    # nss contains certutil which is used to generate a certificate.
+    su - $USER -c "$HOMEBREW_PATH/bin/brew install nss" || fatal "failed to install nss using homebrew"
+fi
 
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
