generate new CA (#1057)
* generate new CA

add a comment

win (installer): create certs dir with access rights

* remove mkcert

* fix test

* no init function

because logger is not initialized when init function is called

* improve debug log

diff --git a/installer/macos/scripts/postinstall b/installer/macos/scripts/postinstall
--- a/installer/macos/scripts/postinstall
+++ b/installer/macos/scripts/postinstall
@@ -12,10 +12,6 @@ export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH
 export MASSASTATION_CONFIG_DIR=/usr/local/share/massastation
 export MASSASTATION_CERT_DIR=/etc/massastation/certs
 
-# Set mkcert download URLs.
-export MKCERT_URL_ARM="https://dl.filippo.io/mkcert/latest?for=darwin/arm64"
-export MKCERT_URL_AMD="https://dl.filippo.io/mkcert/latest?for=darwin/amd64"
-
 # Print error message to stderr and exit with code 1.
 fatal() {
     echo "FATAL: $1" >&2
@@ -46,36 +42,11 @@ set_local_dns() {
     esac
 }
 
-# Generate a certificate for MassaStation.
-generate_certificate() {
-    # If Firefox is installed, we need to install nss to read the certificate.
-    [[ $(find /Applications/ -type d -iname "*Firefox*.app") ]] && (su - $USER -c "$HOMEBREW_PATH/bin/brew install nss" || fatal "nss installation failed. MassaStation won't work on Firefox.")
-
-    ARCH=$(uname -m)
-    if [[ $ARCH == "arm64" ]]; then
-        MKCERT_URL=$MKCERT_URL_ARM
-    else
-        MKCERT_URL=$MKCERT_URL_AMD
-    fi
-
-    curl -sL $MKCERT_URL -o mkcert >&2 || fatal "mkcert download failed."
-    chmod +x mkcert || fatal "mkcert permission change failed."
-    ./mkcert -install || fatal "mkcert installation failed."
-    chmod 644 ~/Library/Application\ Support/mkcert/rootCA.pem ~/Library/Application\ Support/mkcert/rootCA-key.pem || fatal "root certs permission change failed."
-    mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."
-    ./mkcert -cert-file $MASSASTATION_CERT_DIR/cert.pem -key-file $MASSASTATION_CERT_DIR/cert-key.pem station.massa || fatal "mkcert certificate generation failed."
-    chmod 644 $MASSASTATION_CERT_DIR/cert.pem $MASSASTATION_CERT_DIR/cert-key.pem || fatal "certs permission change failed."
-    rm mkcert || fatal "mkcert removal failed."
-}
-
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
 mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/logs || fatal "logs directory creation failed."
+mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."
 
 ping -c 1 -t 1 test.massa >/dev/null 2>&1 || set_local_dns
-
-if [[ ! -f $MASSASTATION_CERT_DIR/cert.pem || ! -f $MASSASTATION_CERT_DIR/cert-key.pem ]]; then
-    generate_certificate
-fi
 
 mv ./uninstall.sh $MASSASTATION_CONFIG_DIR || fatal "uninstall script move failed."
