Fix bash command not found error.

diff --git a/installer/macos/scripts/postinstall b/installer/macos/scripts/postinstall
--- a/installer/macos/scripts/postinstall
+++ b/installer/macos/scripts/postinstall
@@ -25,8 +25,7 @@ fatal() {
 # Check if brew is installed. If not, install it.
 if ! command -v brew &>/dev/null; then
     echo "Installing Brew..."
-    export NONINTERACTIVE=1
-    su - $USER -c "/bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'" || fatal "brew installation failed."
+    su - $USER -c 'NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"' || fatal "brew installation failed."
 else
     echo "Updating Brew..."
     su - $USER -c "brew update" || fatal "brew update failed."
